// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	TalkToAPot = 0,
	TalkToABanana = 1,
	BananaBill = 2,
	HallwayDemo = 3,
	LockedDoor = 4,
}
