// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	TwilitHollow1_Cliff = 0,
	TalkToABanana = 1,
	BananaBill = 2,
	HallwayDemo = 3,
	TwilitHollow2_Rock = 4,
	TwilitHollow4_Box = 5,
	TwilitHollow5_Pond = 6,
	TwilitHollow6_Box2 = 7,
}
